# Generated by Django 3.2.17 on 2023-04-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
